### PR TITLE
Add QuestLines to False Positive Rules

### PR DESCRIPTION
**Pull request by tim-inzitari**
Would fix clustering

### CODE REVIEW

**Comment by beheh** [comment]
The cards have `QUESTLINE` instead - maybe we just check for that?

**Comment by beheh** [comment]
However: this is a false positive rule, which is used to prevent archetypes from collapsing into each other (i.e. quest and non-quest archetypes). Are we sure we can treat questlines as deck-defining as (oldschool) quests?

**Comment by tim-inzitari** [comment]
> The cards have `QUESTLINE` instead - maybe we just check for that?

They do not, EXAMPLE: the questline you would put in your mage deck

>   {
    "artist": "Arthur Bozonnet",
    "cardClass": "MAGE",
    "collectible": true,
    "cost": 1,
    "dbfId": 64488,
    "elite": true,
    "flavor": "After \"the incident,\" the Stockades really had to reevaluate their anti-mage protocols.",
    "id": "SW_450",
    "name": "Sorcerer's Gambit",
    "rarity": "LEGENDARY",
    "set": "STORMWIND",
    "text": "<b>Questline:</b> Cast a Fire, Frost, and Arcane spell. <b>Reward: </b>Draw a spell.",
    "type": "SPELL"
  },

**Comment by tim-inzitari** [comment]
Added test cases for this as well since i forgot to do that

**Pull request merged**
